services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"   # già presente, per eventuale fallback
      - "3000:3000"   # ⬅️ AGGIUNGI QUESTA RIGA
    environment:
      APP_ENV: local
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      DB_FOREIGN_KEYS: "true"
